import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbfbe2",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f2f2d9",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbc9",
        "surface-tint": "#b52424",
        "on-surface-variant": "#5a403e",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb4ac",
        "outline": "#8e706d",
        "on-error-container": "#93000a",
        "secondary-container": "#fed65b",
        "on-primary-fixed-variant": "#92030f",
        "surface-container": "#efefd7",
        "secondary-fixed": "#ffe088",
        "primary-fixed": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#410003",
        "surface-variant": "#e4e4cc",
        "surface-dim": "#dbdcc3",
        "surface-container-low": "#f5f5dc",
        "surface-container-highest": "#e4e4cc",
        "on-tertiary-fixed-variant": "#753401",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed-variant": "#574500",
        "primary-container": "#b22222",
        "on-tertiary-container": "#ffcaad",
        "inverse-surface": "#303221",
        "on-surface": "#1b1d0e",
        "background": "#fbfbe2",
        "on-background": "#1b1d0e",
        "surface-container-high": "#eaead1",
        "on-secondary-container": "#745c00",
        "tertiary": "#723200",
        "on-primary-container": "#ffc8c2",
        "tertiary-fixed-dim": "#ffb68c",
        "outline-variant": "#e2beba",
        "secondary": "#735c00",
        "surface": "#fbfbe2",
        "tertiary-container": "#904917",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#321200",
        "on-tertiary": "#ffffff",
        "primary": "#8f000d",
        "on-secondary-fixed": "#241a00",
        "primary-fixed-dim": "#ffb4ac",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        "3xl": "2.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
